mspanel/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.contrib import admin

from main import views

from adminplus.sites import AdminSitePlus
admin.site = AdminSitePlus()
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^geo/$', 'main.views.target_geo_search'),
    url(r'^request/log/$', 'request.views.log'),
    url(r'^proxy/unactivate/(?P<port>[0-9]+)/', 'main.views.proxy_port_unactivate'),
    url(r'^proxy/activate/(?P<port>[0-9]+)/', 'main.views.proxy_port_activate'),
    url(r'^proxy/stat/', 'main.views.proxy_stat'),
    url(r'^mailing/(?P<mid>[0-9]+)/pic/', 'main.views.mailing_add_url', {'mode': 'pic'}),
    url(r'^mailing/(?P<mid>[0-9]+)/link/', 'main.views.mailing_add_url', {'mode': 'link'}),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

main/views.py
#coding=utf8
import datetime
import json
import time
import random
import string

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.cache import cache
from django.utils import timezone
from django import forms
from django.db import connection

from datetimewidget.widgets import DateTimeWidget

from sender.models import *
from main.models import *

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

def pack(qs, items, sitems, prefix=''):
    if prefix:
        prefix += ' > '
    for i in qs:
        items.append({
            'id': i.get_id(), 
            'text': '%s%s' % (prefix, i.get_name())
        })
        sitems.append(i)

def filt(root):
    class_name = root.__class__.__name__

    if class_name == 'Continent':
        return Country.objects.filter(continent=root)
        
    if class_name == 'Country':
        # return Region.objects.filter(country=root)
        return City.objects.filter(country=root)
    
    if class_name == 'Region':
        return City.objects.filter(region=root)

def target_geo_search(request):
    items = []
    sitems = []
    reset = False
    root = None
    limit = 10
    flag = False

    q = request.GET.get('q').lower().strip()
    r = request.GET.get('r')

    if q.endswith('.'):
        flag = True
        q = q[:-1]

    if r:
        root = Geo.get(r)

        qs = filt(root)
        if q:
            qs = qs.filter(name__istartswith=q)
        
        # raise Exception(qs.count(), str(qs.query))
        items=[];sitems=[]
        pack(qs, items, sitems, root.get_name())
    else:
        for model in Geo.models():
            qs = model.objects.filter(name__istartswith=q)
            pack(qs, items, sitems)

    if flag:
        root = sitems[0]
        reset = True
        
        qs = filt(root)

        items=[];sitems=[]
        pack(qs, items, sitems, root.get_name())

    data = {
        'items': items,
        'total_count': len(items),
        'reset': reset,
        'root': root.get_id() if root else '',
    }
    return HttpResponse(json.dumps(data))

def handle_uploaded_file(f, filename):
    with open(filename, 'wb+') as dest:
        for chunk in f.chunks():
            dest.write(chunk)

def load_accounts(request):
    class UploadForm(forms.Form):
        _file = forms.FileField(label='Файл с аккаунтами', max_length=100)

    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            filename = '/tmp/accounts' + ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(4))
            handle_uploaded_file(request.FILES['_file'], filename)
            t = Task()
            t.load_accounts(filename)
            t.run_now()
            return HttpResponseRedirect('/admin/account/load/')
    else:
        form = UploadForm()

    task = Task.GET('accounts_heatup')
    if 'start' in request.GET:
        task.restart()
        task.run_now()
        time.sleep(1)
        return HttpResponseRedirect('/admin/account/load/')

    if 'stop' in request.GET:
        task.kill()
        time.sleep(1)
        return HttpResponseRedirect('/admin/account/load/')
    ms = MailRuAccount.objects
    
    total = ms.count()
    active = ms.filter(is_active=True).count()
    unactive = ms.filter(is_active=False).count()
    loaded = ms.filter(is_active=True,auth_data__isnull=False).count()

    s = None
    t = Task.GET('load_accounts')
    if t:
        s = t.info

    return render(request, 'load_accounts.html', {
        'form': form,
        's': s,
        'task': task,
        'total': total,
        'active': active,
        'unactive': unactive,
        'loaded': loaded,
    })


def reg_accounts(request):
    from django import forms
    import time

    task = Task.GET('accounts_reg')
    
    idents = [('antigate', 'AntiGate.com'), ('rucaptcha', 'RuCaptcha.com')]
    
    now = timezone.now()
    start = now + datetime.timedelta(minutes=2)
    stop = now + datetime.timedelta(minutes=7)

    class TaskForm(forms.Form):
        thread_count = forms.IntegerField(
            label='Количество потоков', initial=task.get_argument('thread_count'))
        limit = forms.IntegerField(
            label='Количество успехов', initial=task.get_argument('limit'), help_text='0-бесконечно')
        start_now = forms.BooleanField(
            label='Начать сейчас', required=False, initial=task.start_at is None)
        start_at = forms.DateTimeField(
            label='Время начала', required=False, initial=task.start_at or start)
        stop_at = forms.DateTimeField(
            label='Время конца', required=False, initial=task.stop_at or stop)
        captcha_idents = forms.MultipleChoiceField(
            label='Распознавание капчи', choices=idents, initial=task.get_argument('captcha_idents'))
        new_script = forms.BooleanField(
            label='Новый алгоритм (Рамблер)', required=False)

        def clean(self):
            data = super(TaskForm, self).clean()
            
            if not data.get('start_now', False):
                if not data.get('start_at'):
                    self.add_error('start_at', forms.ValidationError('Укажите время начала.'))
            
                if not data.get('stop_at'):
                    self.add_error('stop_at', forms.ValidationError('Укажите время конца.'))
            
            return data

    if task.is_active_proc():
        form = None
    else:
        if request.method == 'POST':
            form = TaskForm(request.POST)
            if form.is_valid():
                if form.cleaned_data['new_script']:
                    task.command = 'account/reg_new.py'
                    task.kill_command = 'account/reg_new.py kill'
                else:
                    task.command = 'account/reg.py'
                    task.kill_command = 'account/reg.py kill'
                task.arguments = {
                    'limit': form.cleaned_data['limit'],
                    'thread_count': form.cleaned_data['thread_count'],
                    'captcha_idents': form.cleaned_data['captcha_idents'],
                }
                task.save()

                if form.cleaned_data['start_now']:
                    task.restart()
                    task.start_at = None
                    task.stop_at = None
                    task.save()
                    task.run_now()
                    time.sleep(1)
                else:
                    task.restart()
                    task.start_at = form.cleaned_data['start_at']
                    task.stop_at = form.cleaned_data['stop_at']
                    task.save()
                
                return HttpResponseRedirect('/admin/account/reg/')

        else:
            form = TaskForm()

    ms = MailRuAccount.objects
    
    total = ms.count()
    active = ms.filter(is_active=True).count()
    unactive = ms.filter(is_active=False).count()
    loaded = ms.filter(is_active=True,auth_data__isnull=False).count()
    generated = ms.filter(sex__isnull=False).count()
    
    logs = TaskLog.objects \
        .filter(task=task) \
        .order_by('-id')[:10]

    if 'stop' in request.GET:
        task.kill()
        time.sleep(1)
        return HttpResponseRedirect('/admin/account/reg/')
    
    try:
        log = TaskLog.objects.get(task=task, pk=request.GET['id'])
    except:
        try:
            log = task.log 
        except:
            log = None
    if log:
        # try:
        started_at, stopped_at = log.get_work_range()
        
        try:
            data = json.loads(log.result)
        except:
            data = None
            stat = None
    
        if data:
            try:
                d = data['download_size'] / 1024.0
                
                if data['counts']['user']:
                    p = (stopped_at-started_at).total_seconds() / float(data['counts']['user'])
                    dp = d / float(data['counts']['user'])
                else:
                    p = 0
                    dp = 0

                l1 = '/admin/main/mailruaccount/?task_log_id__exact=%d' % log.id
                l2 = '/admin/main/mailruaccount/?task_log_id__exact=%d&auth_data__isnull=0' % log.id
                l3 = '/admin/main/mailruaccount/?task_log_id__exact=%d&has_my__exact=1' % log.id
                stat = [
                    ('Время начало', started_at),
                    ('Время конца', stopped_at),
                    ('Зарегистрировано', '<a href="%s">%d</a>' % (l1, data['counts']['user'])),
                    (' - авторизировано', '<a href="%s">%d</a>' % (l2, data['counts']['user_auth_data'])),
                    (' - мой мир', '<a href="%s">%s</a>' % (l3, data['counts'].get('has_my','-'))),
                    ('Попыток', data['try_count']),
                    ('В обработке', data['current']),
                    
                    ('Логины', '---'),
                    ('Предложили логин', data['counts'].get('yes_login', '-')),
                    ('Не предложили логин', data['counts'].get('no_login', '-')),
                    
                    ('Ошибки', '---'),
                    ('Ошибок подряд', data.get('error_count','-')),
                    ('Максимум ошибок подряд', data.get('error_limit','-')),
                    
                    ('Ошибки по видам', '---'),
                    ('Пустая форма', data['counts'].get('error_form', '-')),
                    ('Ошибок сети', data['counts'].get('net_error', '-')),
                    ('Не принято', data['counts'].get('no_reg', '-')),
                    ('Забанено IP (телефон)', data['counts'].get('ban_ip', '-')),

main/templates/domain_stat.html
{% extends "admin/base_site.html" %}
{% load humanize %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}
<head>
  <!-- <meta http-equiv="refresh" content="10" > -->
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="http://www.flotcharts.org/flot/jquery.flot.js"></script>
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>
  <script src="{% static 'js/bootstrap.js' %}"></script>
  {{ form.media }}

  <script src="http://code.highcharts.com/highcharts.js"></script>
  <script src="http://code.highcharts.com/modules/exporting.js"></script>

<script type="text/javascript">
$(function () {
    $('#container').highcharts({
        chart: {
            type: 'spline'
        },
        title: {
            text: '{{ plot_title }}'
        },
        xAxis: {
            type: 'datetime',
            dateTimeLabelFormats: { // don't display the dummy year
                month: '%e.%b',
                year: '%y'
            },
            title: {
                text: 'Date'
            }
        },
        yAxis: {
            title: {
                text: 'кол-во доменов'
            },
        },
        tooltip: {
            headerFormat: '<b>{series.name}</b><br>',
            pointFormat: '{point.x:%e.%b %H:%M}: {point.y}'
        },

        plotOptions: {
            spline: {
                marker: {
                    enabled: true
                }
            }
        },

        series: [{
            data: [
                {% for d, v in plot%}
                [Date.UTC({{ d.year }}, {{ d.month }}, {{ d.day }}, {{ d.hour }}, {{ d.minute }}), {{ v }}], 
                {% endfor %}
            ]
        }]
    });
});
</script>

</head>

<style>
td.digit {text-align:right;}
td {vertical-align:top;}
</style>
<div class="container">

  <div class="row">
    <h3>Фильтр</h3>
    <div class="col-md-4 well">
      <form  action="" method="GET">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input id="submit" name="submit" class="btn btn-default pull-right" type="submit" value="Посмотреть">
      </form>
    </div>
    <div class="col-md-8">
      <h3>Статистика скрипта CHECK</h3>
      <table class="table">  
        <thead>
         <th>&nbsp;</th>
         <th class="digit">запросов (шт)</th>
         <th class="digit">ошибок (%)</th>
         <th class="digit">положительно (%)</th>
         <th class="digit">отрицательно (%)</th>
         <th class="digit">повтор (%)</th>
         <th class="digit">время одного запроса(с)</th>
        </thead>
       {% for key,stat in check_stat %}
       </tr>
        <td>{{ key }}</td>
        {% if stat == None %}
        <td colspan="6"></td>
        {% else %}
        <td class="digit">{{ stat.count|intcomma }}</td>
        <td class="digit"><span title="{{ stat.error|intcomma }}">{{ stat.error_p|floatformat:2|intcomma }}</span></td>
        <td class="digit"><span title="{{ stat.true|intcomma }}">{{ stat.true_p|floatformat:2|intcomma }}</span></td>
        <td class="digit"><span title="{{ stat.false|intcomma }}">{{ stat.false_p|floatformat:2|intcomma }}</span></td>
        <td class="digit"><span title="{{ stat.none|intcomma }}">{{ stat.none_p|floatformat:2|intcomma }}</span></td>
        <td class="digit">{{ stat.avg_time|floatformat:2|intcomma }}</td>
        {% endif %}
       </tr>
       {% endfor %}
      </table>
    </div>
    <div class="col-md-12">
      <h3>График</h3>
      <div id="container" style="min-width: 310px; height: 600px; margin: 0 auto"></div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <h3>Данные по статусам</h3>
      <table class="table">
        <thead>
         <th>Описание</th>
         <th>Статусы</th>
         <th>Сейчас</th>
         <th>Изменение</th>
        </thead>
        {% for name, status, current, change in state %}
          <tr>
           <td>{{ name }}</td>
           <td>{{ status }}</td>
           <td class="digit">
            {{ current|intcomma }}
           </td>
           <td class="digit">
            {% if change == None %}
            -
            {% else %}
            {{ change|intcomma }}
            {% endif %}
           </td>
          </tr>
        {% endfor%}
      </table>
    </div>
  </div>


</div>
{% endblock %}

main/templates/load_accounts.html
{% extends "admin/base_site.html" %}

{% block content %}
{% if s %}
<table>
 <tr><td>Всего</td><td>{{ s.total }}</td></tr>
 <tr><td>Новых</td><td>{{ s.new }}</td></tr>
 <tr><td>Существующих</td><td>{{ s.exist }}</td></tr>
</table>
<hr>
{% endif %}

<div>
<b><i>Формат файла:</i></b><br>
username;password
</div>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Сохранить" />
</form>

<hr>
Всего аккаунтов: {{ total }}<br>
Активных аккаунтов: {{ active }}<br>
НЕактивных аккаунтов: {{ unactive }}<br>
Загружено токенов: {{ loaded }}<br>
<hr>
Загрузка токенов: <a href="/admin/main/task/{{ task.id }}/">{{ task }}</a><br>
{% if task.is_active_proc%}
<img src="/static/admin/img/icon-yes.gif"> Выполняется <a href="?stop">Остановить</a>
{% else %}
<img src="/static/admin/img/icon-no.gif"> Стоит <a href="?start">Запустить</a>
{% endif %}
<br>
Обновлено: {{ task.updated_at }}<br>
Статус: {{ task.status_string }}<br>
{% if task.status == 3 %}
{% autoescape off %}
Ошибка: {{ task.get_exception }}
{% endautoescape %}
{% endif %}
{% endblock %}

main/templates/proxy_stat.html
{% extends "admin/base_site.html" %}

{% block content %}
Host: {{ host }}<br>
<hr>
Random proxy:<br> 
{% if proxy == False %}
 - нет доступных прокси<br>
{% else %}
adderss: {{ proxy.address }}<br> 
type: {{ proxy.type }}<br> 
{% endif %}
<hr>
{% if result %}
<pre>{{ result }}</pre>
<hr>
{% endif %}

<form action="" class="form-inline">
	<div class="form-group">
    	<label>Время перезагрузки:</label>
	 	<input type="number" name="restart_time" value="{{ restart_time }}" class="form-control" step="0.5">
    </div>
	<input type="submit" name="set_restart_time" value="Сохранить" class="btn btn-default">
</form>
<table>
 <thead>
  <th>порт</th>
  <th>статус активности</th>
  <th>перезагрузка</th>
  <th>callback1</th>
  <th>callback2</th>
 </thead>
 {% for s in stat %}
 <tr>
 	<td><a href="/admin/proxy/trafic/{{ s.port }}/">{{ s.port }}</a></td>
 	<td>
 	{% if s.is_active == None %}
 		<img src="/static/admin/img/icon-unknown.gif" alt="None"> неизвестно
 	{% elif s.is_active == False %}
 		<img src="/static/admin/img/icon-no.gif" alt="True"> перезагружается
 	{% else %}
 		<img src="/static/admin/img/icon-yes.gif" alt="True"> активен ({{ s.is_active }})
 	{% endif %}
 	</td>
 	<td><a href="/proxy/stat/?reboot={{ s.port }}&out=1">reboot</a></td>
 	<td><a href="/proxy/activate/{{ s.port }}/">callback1</a></td>
 	<td><a href="/proxy/unactivate/{{ s.port }}/">callback2</a></td>
 </tr>
 {% endfor %}
</table>
{% endblock %}

main/templates/proxy_trafic_stat.html
{% extends "admin/base_site.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="http://www.flotcharts.org/flot/jquery.flot.js"></script>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>
<script src="{% static 'js/bootstrap.js' %}"></script>
{{ form.media }}

<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>

<script type="text/javascript">
$(function () {
    $('#container').highcharts({
        chart: {
            type: 'spline'
        },
        title: {
            text: '{{ plot_title }}'
        },
        xAxis: {
            type: 'datetime',
            dateTimeLabelFormats: { // don't display the dummy year
                month: '%e.%b',
                year: '%y'
            },
            title: {
                text: 'Date'
            }
        },
        yAxis: {
            title: {
                text: 'Мб'
            },
        },
        tooltip: {
            headerFormat: '<b>{series.name}</b><br>',
            pointFormat: '{point.x:%e.%b %H:%M}: {point.y}'
        },

        plotOptions: {
            spline: {
                marker: {
                    enabled: true
                }
            }
        },

        series: [{
            name: 'recieve',
            data: [
                {% for d, v in rx %}
                [Date.UTC({{ d.year }}, {{ d.month }}, {{ d.day }}, {{ d.hour }}, {{ d.minute }}), {{ v }}], 
                {% endfor %}
            ]
        },{
            name: 'transmit',
            data: [
                {% for d, v in tx %}
                [Date.UTC({{ d.year }}, {{ d.month }}, {{ d.day }}, {{ d.hour }}, {{ d.minute }}), {{ v }}], 
                {% endfor %}
            ]
        },{
            name: 'total',
            data: [
                {% for d, v in total %}
                [Date.UTC({{ d.year }}, {{ d.month }}, {{ d.day }}, {{ d.hour }}, {{ d.minute }}), {{ v }}], 
                {% endfor %}
            ]
        }]
    });
});
</script>
<div class="container">
  <div class="row">
    <div class="col-md-4 well">
      <h3>Фильтр</h3>
      <form  action="" method="GET">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input id="submit" name="submit" class="btn btn-default pull-right" type="submit" value="Посмотреть">
      </form>
    </div>
    <div class="col-md-8">
      <h3>График</h3>
      <div id="container" style="min-width: 310px; height: 600px; margin: 0 auto"></div>
    </div>
  </div>
</div>

{% endblock %}

main/templates/reg_accounts.html
{% extends "admin/base_site.html" %}

{% block content %}
Всего аккаунтов: {{ total }}<br>
Генерированных аккаунтов: {{ generated }}<br>
Активных аккаунтов: {{ active }}<br>
НЕактивных аккаунтов: {{ unactive }}<br>
Загружено токенов: {{ loaded }}<br>
<hr>

Регистрация аккаунтов: <a href="/admin/main/task/{{ task.id }}/">{{ task }}</a><br>
{% if task.is_active_proc %}
<img src="/static/admin/img/icon-yes.gif"> Выполняется <a href="?stop">Остановить</a>
{% else %}
<img src="/static/admin/img/icon-no.gif"> Стоит
{% endif %}
<br>

Обновлено: {{ task.updated_at }}<br>

{% if task.status_string %}
Статус: {{ task.status_string }}<br>
{% endif %}

{% if task.start_at %}
Запланированное время начала: {{ task.start_at }}<br>
{% endif %}

{% if task.stop_at %}
Запланированное время конца: {{ task.stop_at }}<br>
{% endif %}


{% if task.status == 3 %}
{% autoescape off %}
Ошибка: {{ task.get_exception }}
{% endautoescape %}
{% endif %}

{% if form %}
<hr>
	<form action="" method="post" enctype="multipart/form-data">
	    {% csrf_token %}
	    <table>
	    	{{ form }}
	    </table>
	    <input type="submit" name='start' value="Запустить" />
	</form>

	<script type="text/javascript" src="/static/admin/js/jquery.js"></script>
	<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
	<script>
	$ = django.jQuery;
	$('#id_start_now').change(function(){
		if ($(this).prop("checked")) {
			$('#id_start_at').closest('tr').hide()
			$('#id_stop_at').closest('tr').hide()
		} else {
			$('#id_start_at').closest('tr').show()
			$('#id_stop_at').closest('tr').show()
		}
	});
	$('#id_start_now').change();
	</script>
{% endif %}

<hr>
<a href="/admin/main/config/?group=account_reg">Параметры скрипта регистрации</a><br>

{% autoescape off %}
{% if stat %}
<hr>
<h3>Статистика</h3>
<table class="table table-hover">
{% for k,v in stat %}
	{% if v == '---' %}
	<tr class="active">
	{% else %}
	<tr>
	{% endif %}
	<td>{{ k }}</td>
	<td>{{ v }}</td>
	</tr>
{% endfor %}
</table>
{% else %}
<b><i>СТАТИСТИКА НЕДОСТУПНА</i></b>
{% endif %}
{{ log.result }}
<hr>
{% endautoescape %}

{% if params %}
<hr>
<h3>Параметры</h3>
<table>
{% for k,v in params %}
	<tr>
	<td>{{ k }}</td>
	<td>{{ v }}</td>
	</tr>
{% endfor %}
</table>
{% endif %}


<hr>
<table class='table'>
 <thead>
  <th>ID</th>
  <th>Начало</th>
  <th>Конец</th>
 </thead>
{% for log in logs %}
<tr>
 <td><a href="?id={{ log.id }}">{{ log.id }}</a></td>
 <td>{{ log.started_at }}</td>
 <td>{{ log.stopped_at }}</td>
</tr>
{% endfor %}
</table>
{% endblock %}